### ISSUE TITLE
Container registry rate-limit protection

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/k8s-harbor#38]
As a container registry administrator, I want to be able to set rate-limit protection to prevent DoS attacks (see [docker-hub rate limit](https://docs.docker.com/docker-hub/download-rate-limit/) as an example).

Note that this feature is not available directly in the Harbor project, see open [issue](https://github.com/goharbor/harbor/issues/3419).

As the k8s-harbor project is intended to deploy Harbor into k8s cluster, the k8s ingress controller is probably the right place to achieve this kind of protection on Harbor.

**Comment by matofeder** [comment]
related to https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/417

**Comment by chess-knight** [comment]
> Note that this feature is not available directly in the Harbor project, see open [issue](https://github.com/goharbor/harbor/issues/3419).

As stated, I didn't find anything different. It seems there is no support in Harbor at all.

> the k8s ingress controller is probably the right place to achieve this kind of protection on Harbor.

I decided to try rate limiting on the ingress controller. There is Ingress NGINX Controller in
SCS K8S reference implementation used. Rate Limiting docs for the Ingress-Nginx are available [here](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting).

> set rate-limit protection to prevent DoS attacks (see [docker-hub rate limit](https://docs.docker.com/docker-hub/download-rate-limit/) as an example)

Ingresses are configured via rate-limit annotations, e.g. `nginx.ingress.kubernetes.io/limit-rps: "1"` means
that ingress will allow only 1 request per second. It is ideal for the *DDoS attacks* mitigation.

We want to rate limit per IP address as DockerHub does. For that, as stated in the ingress-nginx docs, we need client IP.
Client IP is set based on the use of `PROXY protocol` or from the `X-Forwarded-For` header value.
In the SCS reference implementation, proxy protocol for ingress nginx is [enabled by default](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/Release-Notes-R4.md#enabling-the-proxy-protocol-for-nginx-ingress-and-preliminary-support-for-ovn-lb-325).

# Local rate limiting

So I used SCS project [k8s-cluster-api-provider](https://github.com/SovereignCloudStack/k8s-cluster-api-provider) for
the installation of k8s cluster. Next, I deployed Harbor with this k8s-harbor repo. It was deployed with basic settings(I changed only *external url*, exposed it via *ingress* and added *issuer*).

Harbor-helm deploys ingress as follows:
1. one host, e.g. `test-registry.dnation.cloud`
2. multiple paths, e.g. `/ --> harbor-portal:80` or `/v2/ --> harbor-core:80`
3. multiple annotations, e.g. `nginx.ingress.kubernetes.io/proxy-body-size: "0"` sets nginx *client_max_body_size* to *0* which disables checking of request size

Via helm values, we are able to add custom annotations, e.g.:
```yaml
expose:
  type: ingress
  ingress:
    harbor:
      annotations:
        nginx.ingress.kubernetes.io/limit-rps: "100"
```
In this case, we allow 100 requests per second.
There are other useful annotations, such as limit concurrent connections, number of kilobytes per second or limit burst requests
see ingress-nginx [docs](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting).

This approach is ideal for DDoS mitigation, and it is something like DockerHub's [Other limits](https://docs.docker.com/docker-hub/download-rate-limit/#other-limits) - thousands of requests per minute.
But also there are problems with it:
1. These limit counters are not shared between nginx instances in the cluster
   - We cannot configure the proper limit, because it is always `limit * n` where n is the number of nginx pods(which can vary)
2. Only limits per second/minute can be configured which is unappropriated for limits like "200 pulls per 6 hours"

Also, these limits are applied for all paths specified in the ingress(`/`, `/v2/`, `/api/`, ...).
If we want to apply these limits only for specific path(e.g. `/v2/*/manifests/*` - this path is used for [docker hub pull limits](https://docs.docker.com/docker-hub/download-rate-limit/#definition-of-limits)),
create secondary ingress with the same host for that:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/limit-rpm: "1"
  name: harbor-ingress-limit
spec:
  ingressClassName: nginx
  rules:
  - host: test-registry.dnation.cloud
    http:
      paths:
      - backend:
          service:
            name: harbor-core
            port:
              number: 80
        path: /v2/.+/manifests/.+
        pathType: Prefix
  tls:
  - hosts:
    - test-registry.dnation.cloud
    secretName: harbor-crt
```
> In the example above we see used a regex, read more about it [here](https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/).
> There is one warning. When [use-regex](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#use-regex) annotation is used
> the case insensitive regular expression [location modifier](https://nginx.org/en/docs/http/ngx_http_core_module.html#location) will be enforced on ALL paths for a given host regardless of what Ingress they are defined on.
> It means that case insensitive regular expression will be enforced also for existing ingress created by harbor-helm - because of the same host.

# Global rate limiting

These 2 mentioned problems with (Local) rate limiting can be overcome by [nginx global rate limiting](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#global-rate-limiting).
For global limits, we first need to deploy `memcached` - a place where nginx instances share a limit counter:
```bash
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install mycache bitnami/memcached
...
Memcached can be accessed via port 11211 on the following DNS name from within your cluster:

    mycache-memcached.default.svc.cluster.local
```
Next configure nginx ingress(trough configmap) to use this memcached:
```bash
$ kubectl edit cm -n ingress-nginx ingress-nginx-controller
#  data:
#    global-rate-limit-memcached-host: mycache-memcached.default.svc.cluster.local
```
Now the annotations can be used:
```yaml
metadata:
  annotations:
    nginx.ingress.kubernetes.io/global-rate-limit: "2"
    nginx.ingress.kubernetes.io/global-rate-limit-window: "30m"
```
The location in nginx.conf looks like this:
```
location ~* "^/v2/.+/manifests/.+" {
  ...
  rewrite_by_lua_block {
    lua_ingress.rewrite({
      ...
      global_throttle = { namespace = "58b107dcac9d4456a9273cd23415b54e", limit = 2, window_size = 1800, key = { { nil, nil, "remote_addr", nil, }, }, ignored_cidrs = { } },
    })
    ...
  }
  ...
}
```
Above is global rate limit setting - `namespace`(ingress uid without dashes), `limit`, `window_size`(30m = 1800s), `key` is variable do differentiate requests(default is *$remote_addr*), `ignored_cidrs` is empty.

See example docker requests:
```bash
$ docker pull nginx
$ docker tag nginx test-registry.dnation.cloud/library/nginx
$ docker login -u admin test-registry.dnation.cloud
$ docker push test-registry.dnation.cloud/library/nginx
Using default tag: latest
The push refers to repository [test-registry.dnation.cloud/library/nginx]
4fd834341303: Pushed 
5e099cf3f3c8: Pushed 
7daac92f43be: Pushed 
e60266289ce4: Pushed 
4b8862fe7056: Pushed 
8cbe4b54fa88: Pushed 
latest: digest: sha256:6b06964cdbbc517102ce5e0cef95152f3c6a7ef703e4057cb574539de91f72e6 size: 1571
$ docker rmi nginx test-registry.dnation.cloud/library/nginx
$ docker logout test-registry.dnation.cloud
$ docker pull test-registry.dnation.cloud/library/nginx
Using default tag: latest
Error response from daemon: error parsing HTTP 429 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>429 Too Many Requests</title></head>\r\n<body>\r\n<center><h1>429 Too Many Requests</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```
Ingress nginx controller logs(showing only `"$request" $status`):
```bash
$ k logs -n ingress-nginx ingress-nginx-controller-6b94c75599-mkdg8 -f | grep manifests
"PUT /v2/library/nginx/manifests/latest HTTP/1.1" 201
"HEAD /v2/library/nginx/manifests/latest HTTP/1.1" 200
"GET /v2/library/nginx/manifests/sha256:6b06964cdbbc517102ce5e0cef95152f3c6a7ef703e4057cb574539de91f72e6 HTTP/1.1" 429
```
As the limit was set to 2 requests per 30m we can see that the first push(one PUT request) is OK.
But the pull is not working, because there are two requests(HEAD+GET) and we get `429 Too Many Requests`.

As we can see, when we want to limit only pulls, we need to limit only GET requests(see docker [http api v2](https://docs.docker.com/registry/spec/api/) spec for more info).
This is exactly what DockerHub [does](https://docs.docker.com/docker-hub/download-rate-limit/#definition-of-limits).

I searched for a way how to restrict this ingress only to specific request method, but probably without some "hacking"
it is not possible, see this [issue](https://github.com/kubernetes/ingress-nginx/issues/187).

I tried many different ways, but I came up with this "hack"(I copied nginx.conf, and removed global_throttle settings, which disables global rate limiting):
```yaml
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_method != GET) {
        rewrite_by_lua_block {
          lua_ingress.rewrite({
            force_ssl_redirect = false,
            ssl_redirect = true,
            force_no_ssl_redirect = false,
            preserve_trailing_slash = false,
            use_port_in_redirects = false,
            global_throttle = { namespace = "", limit = 0, window_size = 0, key = { }, ignored_cidrs = { } },
          })
          balancer.rewrite()
          plugins.run()
        }
      }
```
Basically, when method != GET, then global rate limiting is not applied. I also copied the whole rewrite_by_lua_block,
because rewrite_by_lua_block generated by the controller contains other useful settings and calls, which will probably be overridden when the if condition matches.

Now the ingress-nginx controller logs look like this(with the same docker steps as above):
```
"PUT /v2/library/nginx/manifests/latest HTTP/1.1" 201
"HEAD /v2/library/nginx/manifests/latest HTTP/1.1" 200
"GET /v2/library/nginx/manifests/sha256:6b06964cdbbc517102ce5e0cef95152f3c6a7ef703e4057cb574539de91f72e6 HTTP/1.1" 200
```
It counts only GET requests, so docker successfully pulls the image. It ends with status 429 only on the third pull.

# Conclusion

Ingress-nginx controller has two ways how to rate limit requests. (Local) rate limiting and global one.

1. Local rate limiting is useful for mitigating DDoS attacks
2. Global rate limiting is useful for limits like "200 pulls per 6 hours".

We can wisely combine these two, and benefit from them. In the above example we showed
how to do that also for specific regex path (`/v2/.+/manifests/.+`), but it can be also more specified
e.g. for specific projects `/v2/library/.+/manifests/.+`. We showed, how it can be furthermore configured
with the nginx configuration snippet(little bit hacky) so probably bigger logic can be applied.

**Comment by chess-knight** [comment]
> I searched for a way how to restrict this ingress only to specific request method, but probably without some "hacking"
it is not possible, see this [issue](https://github.com/kubernetes/ingress-nginx/issues/187).

Traversing mentioned issue and linked issues I find that filtering based on the HTTP method is supported in the ingress controller from nginxinc, concretely by CR VirtualServerRoute, there is an option called [matches](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#match), where routing based on the nginx variable can be specified. E.g.:
```yaml
path: /coffee
matches:
- conditions:
  - variable: $request_method
    value: POST
```

Also, what in my opinion is more important is, that I found http method based routing in the Kubernetes  Gateway API. The option is also called [matches](https://gateway-api.sigs.k8s.io/api-types/httproute/#matches) and it can be specified in the HTTPRoute resource. For example, see [this](https://gateway-api.sigs.k8s.io/api-types/httproute/#backendrefs-optional) section. E.g.:
```yaml
rules:
- matches:
  - path:
      type: PathPrefix
      value: /some/thing
    method: GET
```

**Comment by matofeder** [comment]
Hello @chess-knight 

Thank you for your excellent research!

Great to know that is also possible to set up limits like "200 pulls per 6 hours" using global rate limiting. 

IMO We could consider setting up reasonable defaults for local rate limiting for mitigating DDoS attacks via ingress resource. 

This could be beneficial for any deployment of SCS Harbor. 

Most probably we should investigate how to set up local rate limiting for Harbor as I'm not aware of any recommendations/best practices available for this kind of setup.
